wifi_ssid = 'Your SSID'
wifi_password = 'Your Password'
route_b_id = 'Route-B ID'
route_b_password = 'Route-B Password'
inventory_id = 'inventory ID'
inventory_password = 'inventory password'
powerbi_url = 'PowerBI URL'